baseURL = 'https://matt-valdez.github.io'
languageCode = 'en-us'
title = 'Matt Valdez - Software Engineer'
gitRepo = 'https://github.com/matt-valdez/matt-valdez.github.io'

[module]
  [[module.imports]]
    path =  'github.com/hugo-toha/toha/v4'

[params]
  [params.features]
    [params.features.analytics]
      enabled = false
    [params.features.newsletter]
      enable = false 
